myproject/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('', include(('home.urls', 'home'), namespace='home')),
]

myproject/blog/home/urls.py
from django.urls import path
from home.views import IndexView
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

myproject/blog/users/urls.py
from django.urls import path
from users.views import RegisterView, ForgetPasswordView, WriteBlogView
from users.views import UserCenterView

urlpatterns = [
    # 参数1：路由
    # 参数2：视图函数
    # 参数3：路由名，方便通过reverse来获取路由
    path('register/', RegisterView.as_view(), name='register'),
    path('forgetpassword/', ForgetPasswordView.as_view(),name='forgetpassword'),
    path('center/', UserCenterView.as_view(), name='center'),
    path('writeblog/', WriteBlogView.as_view(), name='writeblog'),
]

myproject/blog/home/models.py
from django.db import models

# Create your models here.

myproject/blog/users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    mobile = models.CharField(max_length=11, unique=True, blank=False, null=False)
    # user_desc = models.CharField(max_length=500, blank=True, null=False)

    class Meta:
        db_table = 'tb_users'
        verbose_name = '用户管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.mobile

myproject/blog/home/views.py
from django.shortcuts import render
from django.views import View

class IndexView(View):
    """首页广告"""

    def get(self, request):
        """提供首页广告界面"""
        return render(request, 'index.html')

myproject/blog/users/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View
from django.http.response import HttpResponseBadRequest
import re

class RegisterView(View):

    def get(self, request):

        return render(request, 'register.html')

    def post(self, request):
        # 接收参数
        mobile = request.POST.get('mobile')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')

        # 判断参数是否齐全
        if not all([mobile, password, password2]):
            return HttpResponseBadRequest('缺少必传参数')
        # 判断手机号是否合法
        if not re.match(r'^1[3-9]\d{9}$', mobile):
            return HttpResponseBadRequest('请输入正确的手机号码')
        # 判断密码是否是8-20个数字
        if not re.match(r'^[0-9A-Za-z]{8,20}$', password):
            return HttpResponseBadRequest('请输入8-20位的密码')
        # 判断两次密码是否一致
        if password != password2:
            return HttpResponseBadRequest('两次输入的密码不一致')
        else:
            return render(request, 'forget_password.html')

        # 响应注册结果

class ImageCodeView(View):

    def get(self,request):

        return HttpResponseBadRequest('成功')

from django.views import View

class ForgetPasswordView(View):

    def get(self, request):

        return render(request, 'forget_password.html')

class UserCenterView(View):

    def get(self,request):

        return render(request,'center.html')

class WriteBlogView(View):

    def get(self,request):

        return render(request,'write_blog.html')

myproject/blog/templates/center.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title> 用户信息 </title>
    {% load static %}
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入vuejs -->
     <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
</head>

<body>
<div id="app">

<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- 导航栏商标 -->
        <div>
            <a class="navbar-brand" href="index.html">个人博客</a>
        </div>
    </div>
    <!--登录/个人中心-->
    <div class="navbar-collapse">
        <ul class="nav navbar-nav">
            <!-- 如果用户已经登录，则显示用户名下拉框 -->
            <li class="nav-item dropdown" v-if="is_login">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">admin</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block" v-show="show_menu">
                    <a class="dropdown-item" href="write_blog.html">写文章</a>
                    <a class="dropdown-item" href='./center.html'>个人信息</a>
                    <a class="dropdown-item" href='#'>退出登录</a>
                </div>
            </li>
            <!-- 如果用户未登录，则显示登录按钮 -->
            <li class="nav-item" v-else>
                <a class="nav-link" href="../static/login.html">登录</a>
            </li>

        </ul>
    </div>
</nav>

<!--content-->
<div class="container" style="margin-bottom: 20px">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" enctype="multipart/form-data">
                    <!-- username -->
                <div class="form-group col-md-4">
                    <label for="username">用户名</label>
                    <input type="text" class="form-control" id="username" name="username" value="admin" >
                </div>
                <!--<br><h5 class="col-md-4">暂无头像</h5><br>-->
                <br> <div class="col-md-4">头像</div>
                <img src="../static/img/mei.png" style="max-width: 20%;" class="col-md-4"><br>
                    <!-- avatar -->
                    <div class="form-group col-md-4">
                        <label for="avatar">上传头像</label>
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>

                    <!-- phone -->
                    <div class="form-group col-md-4">
                        <label for="phone">电话</label>
                        <input type="text" class="form-control" disabled="disabled" id="phone" name="phone" value="">
                    </div>
                    <!-- desc -->
                    <div class="form-group col-md-4">
                        <label for="desc">简介</label>
                        <!-- 文本区域 -->
                        <textarea type="text" class="form-control" id="desc" name="desc" rows="12" ></textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary" style="margin-left: 12px" >修改</button>
                </form>
            </div>
        </div>
    </div>


<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ qiruihua</h5>
    </div>
</footer>
</div>
<!-- 引入js -->
<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/center.js' %}"></script>
</body>

</html>

myproject/blog/templates/index.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title>首页</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="../static/bootstrap/css/bootstrap.min.css">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="../static/md_css/monokai.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!--导入css-->
    <link rel="stylesheet" href="../static/common/common.css">
    <link rel="stylesheet" href="../static/common/jquery.pagination.css">
    <!-- 引入vuejs -->
    <script type="text/javascript" src="../static/js/vue-2.5.16.js"></script>
    <script type="text/javascript" src="../static/js/axios-0.18.0.min.js"></script>
    <script type="text/javascript" src="../static/js/jquery-1.12.4.min.js"></script>
</head>

<body>
<div id="app">
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="container">
        <!-- 导航栏商标 -->
        <div>
            <a class="navbar-brand" href="./index.html">个人博客</a>
        </div>
        <!-- 分类 -->
        <div class="collapse navbar-collapse">
            <div>
                <ul class="nav navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link mr-2" href="#">Python</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mr-2" href="#">Java</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mr-2" href="#">C</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mr-2" href="#">C++</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!--登录/个人中心-->
    <div class="navbar-collapse">
            <ul class="nav navbar-nav">
                <!-- 如果用户已经登录，则显示用户名下拉框 -->
                <li class="nav-item dropdown" v-if="is_login">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">admin</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block" v-show="show_menu">
                       <a class="dropdown-item" href="{% url 'users:writeblog' %}">写文章</a>
                        <a class="dropdown-item" href='{% url 'users:center'%}'>个人信息</a>

                    </div>
                </li>
                <!-- 如果用户未登录，则显示登录按钮 -->
                <li class="nav-item" v-else>
                    <a class="nav-link" href="../static/login.html">登录</a>
                </li>
            </ul>
        </div>
</nav>

<!-- content -->
<div class="container">
    <!-- 列表循环 -->
    <div class="row mt-2">
            <!-- 文章内容 -->
            <!-- 标题图 -->
            <div class="col-3">
                <img src="../static/img/1.jpg" alt="avatar" style="max-width:100%; border-radius: 20px">
            </div>
            <div class="col">
                <!-- 栏目 -->
                <a  role="button" href="#" class="btn btn-sm mb-2 btn-warning">Python</a>
            <!-- 标签 -->
                <span>
                        <a href="#" class="badge badge-secondary">Django</a>
                </span>
                <!-- 标题 -->
                <h4>
                    <b><a href="../static/detail.html" style="color: black;">如何更好的学习Django呢？</a></b>
                </h4>
                <!-- 摘要 -->
                <div>
                    <p style="color: gray;">
                        Python下有许多款不同的 Web 框架。Django是重量级选手中最有代表性的一位。许多成功的网站和APP都基于Django。Django是一个开放源代码的Web应用框架，由Python写成。
                    </p>
                </div>
                <!-- 注脚 -->
                <p>
                    <!-- 查看、评论、时间 -->
                    <span><i class="fas fa-eye" style="color: lightskyblue;"></i>590&nbsp;&nbsp;&nbsp;</span>
                    <span><i class="fas fa-comments" style="color: yellowgreen;"></i>11&nbsp;&nbsp;&nbsp;</span>
                    <span><i class="fas fa-clock" style="color: pink;"></i>2019-10-22</span>
                </p>
            </div>
            <hr style="width: 100%;"/>
    </div>

    <div class="row mt-2">
        <!-- 文章内容 -->
        <!-- 标题图 -->
        <div class="col-3">
            <img src="../static/img/1.jpg" alt="avatar" style="max-width:100%; border-radius: 20px">
        </div>
        <div class="col">
            <!-- 栏目 -->
            <a  role="button" href="#" class="btn btn-sm mb-2 btn-warning">Python</a>
            <!-- 标签 -->
            <span>
                        <a href="#" class="badge badge-secondary">Django</a>
                </span>
            <!-- 标题 -->
            <h4>
                <b><a href="../static/detail.html" style="color: black;">如何更好的学习Django呢？</a></b>
            </h4>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    Python下有许多款不同的 Web 框架。Django是重量级选手中最有代表性的一位。许多成功的网站和APP都基于Django。Django是一个开放源代码的Web应用框架，由Python写成。
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 转发、评论、时间 -->
                <span><i class="fas fa-eye" style="color: lightskyblue;"></i>590&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-comments" style="color: yellowgreen;"></i>11&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-clock" style="color: pink;"></i>2019-10-22</span>
            </p>
        </div>
        <hr style="width: 100%;"/>
    </div>

    <div class="row mt-2">
        <!-- 文章内容 -->
        <!-- 标题图 -->
        <div class="col-3">
            <img src="../static/img/1.jpg" alt="avatar" style="max-width:100%; border-radius: 20px">
        </div>
        <div class="col">
            <!-- 栏目 -->
            <a  role="button" href="#" class="btn btn-sm mb-2 btn-warning">Python</a>
            <!-- 标签 -->
            <span>
                        <a href="#" class="badge badge-secondary">Django</a>
                </span>
            <!-- 标题 -->
            <h4>
                <b><a href="../static/detail.html" style="color: black;">如何更好的学习Django呢？</a></b>
            </h4>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    Python下有许多款不同的 Web 框架。Django是重量级选手中最有代表性的一位。许多成功的网站和APP都基于Django。Django是一个开放源代码的Web应用框架，由Python写成。
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 转发、评论、时间 -->
                <span><i class="fas fa-eye" style="color: lightskyblue;"></i>590&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-comments" style="color: yellowgreen;"></i>11&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-clock" style="color: pink;"></i>2019-10-22</span>
            </p>
        </div>
        <hr style="width: 100%;"/>
    </div>

    <div class="row mt-2">
        <!-- 文章内容 -->
        <!-- 标题图 -->
        <div class="col-3">
            <img src="../static/img/1.jpg" alt="avatar" style="max-width:100%; border-radius: 20px">
        </div>
        <div class="col">
            <!-- 栏目 -->
            <a  role="button" href="#" class="btn btn-sm mb-2 btn-warning">Python</a>
            <!-- 标签 -->
            <span>
                        <a href="#" class="badge badge-secondary">Django</a>
                </span>
            <!-- 标题 -->
            <h4>
                <b><a href="../static/detail.html" style="color: black;">如何更好的学习Django呢？</a></b>
            </h4>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    Python下有许多款不同的 Web 框架。Django是重量级选手中最有代表性的一位。许多成功的网站和APP都基于Django。Django是一个开放源代码的Web应用框架，由Python写成。
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 转发、评论、时间 -->
                <span><i class="fas fa-eye" style="color: lightskyblue;"></i>590&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-comments" style="color: yellowgreen;"></i>11&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-clock" style="color: pink;"></i>2019-10-22</span>
            </p>
        </div>
        <hr style="width: 100%;"/>
    </div>

    <div class="row mt-2">
        <!-- 文章内容 -->
        <!-- 标题图 -->
        <div class="col-3">
            <img src="../static/img/1.jpg" alt="avatar" style="max-width:100%; border-radius: 20px">
        </div>
        <div class="col">
            <!-- 栏目 -->
            <a  role="button" href="#" class="btn btn-sm mb-2 btn-warning">Python</a>
            <!-- 标签 -->
            <span>
                        <a href="#" class="badge badge-secondary">Django</a>
                </span>
            <!-- 标题 -->
            <h4>
                <b><a href="../static/detail.html" style="color: black;">如何更好的学习Django呢？</a></b>
            </h4>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    Python下有许多款不同的 Web 框架。Django是重量级选手中最有代表性的一位。许多成功的网站和APP都基于Django。Django是一个开放源代码的Web应用框架，由Python写成。
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 转发、评论、时间 -->
                <span><i class="fas fa-eye" style="color: lightskyblue;"></i>590&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-comments" style="color: yellowgreen;"></i>11&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-clock" style="color: pink;"></i>2019-10-22</span>
            </p>
        </div>
        <hr style="width: 100%;"/>
    </div>
    <!-- 页码导航 -->
    <div class="pagenation" style="text-align: center">
        <div id="pagination" class="page"></div>
    </div>
</div>

<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ qiruihua</h5>
    </div>
</footer>
</div>

<!-- 引入js -->
<script type="text/javascript" src="../static/js/host.js"></script>
<script type="text/javascript" src="../static/js/common.js"></script>
<script type="text/javascript" src="../static/js/index.js"></script>
<script type="text/javascript" src="../static/js/jquery.pagination.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('#pagination').pagination({
            currentPage: 15,
            totalPage: 30,
            callback:function (current) {

                location.href = '/';
            }
        })
    });
</script>
</body>
</html>

myproject/blog/templates/register.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title>注册</title>
    {% load static %}
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入vuejs -->
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
</head>
<body>
<div id="app">


<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- 导航栏商标 -->
        <div>
            <a class="navbar-brand" href="index.html">个人博客</a>
        </div>
    </div>
    <!--登录/个人中心-->
    <div class="navbar-collapse">
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="../static/login.html">登录</a>
            </li>
        </ul>
    </div>
</nav>
<!--content-->
<div class="container" style="height: 600px;margin-top: 20px">
    <div class="row" >
        <div class="col-12">
            <div class="col-6">
                <form class="login" id="login_form" method="POST">
                    {% csrf_token %}
                    <!--手机号-->
                    <div class="form-group">
                        <label >手机号: </label>
                        <div class="col-lg-6">
                            <input type="text" name="mobile" placeholder="请输入手机号" autofocus="autofocus" required
                                   id="id_login" class="form-control" v-model="mobile" />
                        </div>
                        <small class="form-text text-muted ml-1" v-show="mobile_error" >[[mobile_error_message]]</small>
                    </div>
                    <!--密码-->
                    <div class="form-group">
                        <label >密码:</label>
                        <div class="col-lg-6">
                            <input type="password" name="password" placeholder="请输入密码" required  class="form-control" v-model="password" @blur="check_password" />
                        </div>
                        <small class="form-text text-muted ml-1" v-show="password_error" >[[password_error_message]]</small>
                    </div>
                    <!--确认密码-->
                    <div class="form-group">
                        <label >确认密码:</label>
                        <div class="col-lg-6">
                            <input type="password" name="password2" placeholder="请输入确认密码" required  class="form-control" v-model="password2" @blur="check_password2"/>
                        </div>
                        <small class="form-text text-muted ml-1" v-show="password2_error" >[[password2_error_message]]</small>
                    </div>
                    <a class="nav-link" href="{% url 'home:index' %}" style="width: 70px; height: 40px; background-color: #007bff;font-size: 1rem;color: #fff;display: inline-block; border-radius: .25rem">注册</a>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ qiruihua</h5>
    </div>
</footer>
</div>
<!-- 引入js -->
<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
</body>
</html>

myproject/blog/templates/write_blog.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title> 写文章 </title>
    {% load static %}
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="../static/md_css/monokai.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!-- 引入vuejs -->
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
</head>

<body>
<div id="app">
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- 导航栏商标 -->
        <div>
            <a class="navbar-brand" href="index.html">个人博客</a>
        </div>
    </div>
    <!--登录/个人中心-->
    <div class="navbar-collapse">
        <ul class="nav navbar-nav">
            <!-- 如果用户已经登录，则显示用户名下拉框 -->
            <li class="nav-item dropdown" v-if="is_login">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">admin</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block" v-show="show_menu">
                    <a class="dropdown-item" href="{% url 'users:writeblog' %}">写文章</a>
    <a class="dropdown-item" href='{% url 'users:center'%}'>个人信息</a>
    <a class="dropdown-item" href='{% url 'users:center' %}'>退出登录</a>
                </div>
            </li>
            <!-- 如果用户未登录，则显示登录按钮 -->
            <li class="nav-item" v-else>
                <a class="nav-link" href="../static/login.html">登录</a>
            </li>
        </ul>
    </div>
</nav>

<!-- 写文章表单 -->
<div class="container" style="margin-bottom: 20px">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" enctype="multipart/form-data">
                <!-- 文章标题图 -->
                <div class="form-group">
                    <label for="avatar">标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar" >
                </div>

                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                
                <!-- 文章栏目 -->
                <div class="form-group">
                    <label for="category">栏目</label>
                    <select class="form-control col-3" id="category" name="category">
                            <option value="none">请选择栏目..</option>
                        
                            <option value="1">Django</option>
                        
                            <option value="2">Java</option>
                        
                            <option value="3">HTML</option>
                        
                    </select>
                </div>

                <!-- 文章标签 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="tags">标签</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control col-3" id="tags" name="tags" >
                </div>
                <!-- 文章摘要 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="sumary">文章摘要</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="sumary" name="sumary">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <!--<textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>-->
                    <textarea cols="40" id="id_body" name="content" rows="10" required data-processed="0" :data-config="data_config" data-external-plugin-resources="[]" data-id="id_body" data-type="ckeditortype">
                        </textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>

<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ qiruihua</h5>
    </div>
</footer>
</div>
<!--ckeditor-->
  <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}" data-ckeditor-basepath="{% static 'ckeditor/ckeditor/' %}" id="ckeditor-init-script"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <!-- 引入js -->
    <script type="text/javascript" src="{% static 'js/host.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/write_blog.js' %}"></script>
</body>

</html>